#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
test -f "$ROOT/profiles/devices/pipa"
test -f "$ROOT/profiles/editions/nemomobile"
test -f "$ROOT/profiles/overlays/pipa/overlay.txt"
test -f "$ROOT/profiles/overlays/nemomobile/overlay.txt"
test -f "$ROOT/scripts/inject-full-packages.sh"
test -f "$ROOT/scripts/configure-pipa-hardware.sh"
test -f "$ROOT/docs/upstream-nemo-image.md"
grep -q 'nemo-device-pipa' "$ROOT/profiles/devices/pipa"
grep -q 'linux-pipa' "$ROOT/profiles/devices/pipa"
grep -q 'xiaomi-pipa-firmware' "$ROOT/profiles/devices/pipa"
grep -q 'pipa-sound-conf' "$ROOT/profiles/devices/pipa"
grep -q 'pipa-sensors' "$ROOT/profiles/devices/pipa"
grep -q 'rmtfs' "$ROOT/profiles/devices/pipa"
grep -q 'hexagonrpc' "$ROOT/profiles/devices/pipa"
grep -q 'libssc' "$ROOT/profiles/devices/pipa"
grep -q 'qrtr' "$ROOT/profiles/devices/pipa"
test -f "$ROOT/scripts/build-glacier-extra-apps.sh"
test -f "$ROOT/sparse/usr/bin/nemo-app-fallback"
test -f "$ROOT/sparse/usr/share/applications/glacier-browser.desktop"
test -f "$ROOT/sparse/usr/share/applications/glacier-music.desktop"
test -f "$ROOT/sparse/usr/share/applications/glacier-camera.desktop"
grep -q 'glacier-browser' "$ROOT/profiles/editions/nemomobile"
grep -q 'angelfish' "$ROOT/profiles/editions/nemomobile"
echo "OK: pipa full-image recipe present"
